# Generated by Django 2.2.4 on 2021-09-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplegrocery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_cvv',
        ),
    ]
